// Generates src/environments/version.ts with build-time metadata.
// Runs automatically before `dev`/`build`/`watch` and after `install`
// (see package.json scripts). The output file is gitignored.
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));

function git(args) {
  try {
    return execSync(`git ${args}`, {
      cwd: root,
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
  } catch {
    return '';
  }
}

const commit = git('rev-parse --short HEAD') || 'unknown';
const buildDate = new Date().toISOString().slice(0, 10); // YYYY-MM-DD (UTC)

const contents = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit.
// Regenerated before every \`dev\`/\`build\`; this file is gitignored.
export const versionInfo = {
  version: '${pkg.version}',
  buildDate: '${buildDate}',
  commit: '${commit}',
} as const;
`;

writeFileSync(resolve(root, 'src/environments/version.ts'), contents);
console.log(`[generate-version] ${pkg.version} (${commit}) built ${buildDate}`);
